In [1]:
import numpy as np
import pandas as pd

# Personality Scores Dataset

In [2]:
pscores_df = pd.read_csv('personality_scores.csv', delimiter=';')
pscores_df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pscores_df.isnull().sum()

for score in pscores_df.isnull():
    if "Unnamed" in score:
        del pscores_df[score]
        
pscores_df

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(4, 1)","(5, 3)","(1, 5)","(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 5)",NaN
1551,1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 3)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 3)",NaN
1552,1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(4, 5)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN
1553,1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 3)","(2, 3)","(1, 1)","(5, 1)","(4, 3)",NaN
1554,1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,"(3, 5)","(4, 3)","(5, 3)","(1, 3)","(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 3)",NaN

In [4]:

def eda(dataframe):
    print(f'missing values: {dataframe.isnull().sum()}')
    print(f'dataframe index: {dataframe.index}')
    print(f'dataframe datatypes: {dataframe.dtypes}')
    print(f'dataframe shape: {dataframe.shape}')
    print(f'dataframe describe: {dataframe.describe}')

In [5]:
pscores_df = pscores_df.set_index('ID')
pscores_df.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],IPIP_HIGH_RISK
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN

In [6]:
pscores_df.columns

Index(['Section 5 of 6 [I am always prepared.]',
       'Section 5 of 6 [I am easily disturbed.]',
       'Section 5 of 6 [I am exacting (demanding) in my work.]',
       'Section 5 of 6 [I am full of ideas.]',
       'Section 5 of 6 [I am interested in people.]',
       'Section 5 of 6 [I am not interested in abstract ideas.]',
       'Section 5 of 6 [I am not interested in other people's problems.]',
       'Section 5 of 6 [I am not really interested in others.]',
       'Section 5 of 6 [I am quick to understand things.]',
       'Section 5 of 6 [I am quiet around strangers.]',
       'Section 5 of 6 [I am relaxed most of the time.]',
       'Section 5 of 6 [I am the life of the party.]',
       'Section 5 of 6 [I change my mood a lot.]',
       'Section 5 of 6 [I do not have a good imagination.]',
       'Section 5 of 6 [I don't like to draw attention to myself.]',
       'Section 5 of 6 [I don't mind being the center of attention.]',
       'Section 5 of 6 [I don't talk a lot.]',
       'Section 5 of 6 [I feel comfortable around people.]',
       'Section 5 of 6 [I feel little concern for others.]',
       'Section 5 of 6 [I feel others' emotions.]',
       'Section 5 of 6 [I follow a schedule.]',
       'Section 5 of 6 [I get chores done right away.]',
       'Section 5 of 6 [I get irritated easily.]',
       'Section 5 of 6 [I get stressed out easily.]',
       'Section 5 of 6 [I get upset easily.]',
       'Section 5 of 6 [I have a rich vocabulary.]',
       'Section 5 of 6 [I have a soft (kind) heart.]',
       'Section 5 of 6 [I have a vivid imagination.]',
       'Section 5 of 6 [I have difficulty understanding abstract ideas.]',
       'Section 5 of 6 [I have excellent ideas.]',
       'Section 5 of 6 [I have frequent mood swings.]',
       'Section 5 of 6 [I have little to say.]',
       'Section 5 of 6 [I insult people.]',
       'Section 5 of 6 [I keep in the background.]',
       'Section 5 of 6 [I leave my belongings lying around.]',
       'Section 5 of 6 [I like order.]',
       'Section 5 of 6 [I make a mess of things.]',
       'Section 5 of 6 [I make people feel at ease.]',
       'Section 5 of 6 [I neglect my duties.]',
       'Section 5 of 6 [I often feel blue (down).]',
       'Section 5 of 6 [I often forget to put things back in their proper place]',
       'Section 5 of 6 [I pay attention to details.]',
       'Section 5 of 6 [I seldom feel blue (down).]',
       'Section 5 of 6 [I spend time reflecting on things.]',
       'Section 5 of 6 [I start conversations.]',
       'Section 5 of 6 [I sympathize with others' feelings.]',
       'Section 5 of 6 [I take time out for others.]',
       'Section 5 of 6 [I talk to a lot of different people at parties.]',
       'Section 5 of 6 [I use difficult words.]',
       'Section 5 of 6 [I worry about things.]', 'IPIP_HIGH_RISK'],
      dtype='object')

In [7]:
import re

In [8]:
cols = []

for col in pscores_df.columns:
    if '[' in col:
            
        first_bracket = col.index('[') 
        last_bracket = col.index(']')
        new_col = col[first_bracket+1:last_bracket]
        cols.append(new_col)
    else:
        cols.append(col)
    
pscores_df.columns = cols
pscores_df.head()

,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,I am quiet around strangers.,...,I pay attention to details.,I seldom feel blue (down).,I spend time reflecting on things.,I start conversations.,I sympathize with others' feelings.,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.,IPIP_HIGH_RISK
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN

# Department's Dataset

In [9]:
dpt_df = pd.read_csv('departments.csv', delimiter=';')
dpt_df.describe(include='all')

                 ID Department
count   1555.000000       1555
unique          NaN          6
top             NaN   Strategy
freq            NaN        449
mean     777.000000        NaN
std      449.034149        NaN
min        0.000000        NaN
25%      388.500000        NaN
50%      777.000000        NaN
75%     1165.500000        NaN
max     1554.000000        NaN

In [10]:
dpt_df = dpt_df.set_index('ID')
dpt_df.head()

   Department
ID
0        Data
1        Data
2        Data
3        Data
4        Data

# Calculating Personality Scores

In [11]:


catogories = {
        1: {
            "name": "Extraversion",
            "code": 1
           },
        2: {
            "name":"Agreeableness",
            "code": 2
            },
        3: {
            "name":"Conscientiousness",
            "code": 3
        },
        4: {
            "name":"Neuroticism",
            "code": 4
        },
        5: {
            "name":"Intellect/Imagination",
            "code": 5
            }
        }

def sum_personality(item, code, data):
    count = 0
    for column in data.columns:
        score = item[column]
        if type(score) == str:
            result = int(score[4])
            if int(score[1]) == catogories[code]["code"]:
                count += result
    return count

In [12]:
for cat in catogories:

    pscores_df[catogories[cat]['name']] = pscores_df.apply(lambda row: sum_personality(row, cat, pscores_df), axis=1)
    
pscores_df.head()

,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,I am quiet around strangers.,...,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.,IPIP_HIGH_RISK,Extraversion,Agreeableness,Conscientiousness,Neuroticism,Intellect/Imagination
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,30,40,48,36,42
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN,42,46,46,40,42
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,40,40,38,42
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN,30,38,38,40,38
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,34,46,38,36

# Merging Datasets

In [13]:
dpt_pscores = dpt_df.join(pscores_df)

In [14]:
dpt_pscores.head()

,Department,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,...,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.,IPIP_HIGH_RISK,Extraversion,Agreeableness,Conscientiousness,Neuroticism,Intellect/Imagination
ID,,,,,,,,,,,,,,,,,,,,,
0,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,30,40,48,36,42
1,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN,42,46,46,40,42
2,Data,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,40,40,38,42
3,Data,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN,30,38,38,40,38
4,Data,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,34,46,38,36

In [15]:
# for col in dpt_pscores.columns:
    
#     if 'I ' in col:
#         sum_personality(dpt_pscores[col])
    
# catogories

for row in range(0, 1555):
    
    for cat in dpt_pscores.columns:
        
#         print(dpt_pscores.iloc[row][cat])
        
        if 'I ' in dpt_pscores[cat]:
            sum_personality(dpt_pscores, dpt_pscores.iloc[row][cat], cat)
    
dpt_pscores

,Department,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,...,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.,IPIP_HIGH_RISK,Extraversion,Agreeableness,Conscientiousness,Neuroticism,Intellect/Imagination
ID,,,,,,,,,,,,,,,,,,,,,
0,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,30,40,48,36,42
1,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN,42,46,46,40,42
2,Data,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,40,40,38,42
3,Data,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN,30,38,38,40,38
4,Data,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,34,46,38,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,Web dev,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 3)","(1, 1)","(5, 1)","(4, 5)",NaN,32,48,38,44,44
1551,Web dev,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 3)",NaN,40,48,40,44,34
1552,Web dev,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN,42,44,40,46,48
1553,Web dev,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 3)","(1, 1)","(5, 1)","(4, 3)",NaN,36,38,48,36,44
1554,Web dev,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,"(2, 3)","(1, 1)","(5, 1)","(4, 3)",NaN,22,44,42,40,30

In [16]:
dpt_pscores.drop_duplicates()

,Department,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,...,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.,IPIP_HIGH_RISK,Extraversion,Agreeableness,Conscientiousness,Neuroticism,Intellect/Imagination
ID,,,,,,,,,,,,,,,,,,,,,
0,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,30,40,48,36,42
1,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN,42,46,46,40,42
2,Data,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,40,40,38,42
3,Data,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 1)",NaN,30,38,38,40,38
4,Data,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",NaN,28,34,46,38,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,Web dev,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 3)","(1, 1)","(5, 1)","(4, 5)",NaN,32,48,38,44,44
1551,Web dev,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 3)",NaN,40,48,40,44,34
1552,Web dev,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",NaN,42,44,40,46,48
1553,Web dev,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 3)","(1, 1)","(5, 1)","(4, 3)",NaN,36,38,48,36,44
1554,Web dev,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,"(2, 3)","(1, 1)","(5, 1)","(4, 3)",NaN,22,44,42,40,30

# High Risk vs Low Risk

In [17]:
is_high_risk = (dpt_pscores["Neuroticism"] < 30) & (dpt_pscores["Conscientiousness"] < 30) & (dpt_pscores["Agreeableness"] < 30)
high_risk = dpt_pscores[is_high_risk]
high_risk["IPIP_HIGH_RISK"] = 'high_risk'

# low_risk = dpt_pscores[]
high_risk[["Department"]]

/home/wonderboy/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

       Department
ID
881          Data
1197  Copywriting

In [18]:
is_low_risk = (dpt_pscores["Neuroticism"] >= 30) & (dpt_pscores["Conscientiousness"] >= 30) & (dpt_pscores["Agreeableness"] >= 30)
low_risk = dpt_pscores[is_low_risk]
low_risk["IPIP_HIGH_RISK"] = 'low_risk'

low_risk.Department.unique()

/home/wonderboy/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

array(['Data', 'Web Dev', 'Copywriting', 'Design', 'Strategy', 'Web dev'],
      dtype=object)

In [32]:
risks_df = {
    'risk': ['Low Risk', 'High Risk']
}

def count_risks (dataframe, department):
    num_of_people = len(dataframe[dataframe.Department == department])
    
    if num_of_people.index == None:
        num_of_people = 0

    if department in risks_df:
        risks_df[department].append(num_of_people)
    else:
        risks_df[department] = [num_of_people]

In [33]:
for dpt in low_risk.Department.unique():
    count_risks(low_risk, dpt)
    
for dpt in high_risk.Department.unique():
    count_risks(high_risk, dpt)
    
risks_df

AttributeError: 'int' object has no attribute 'index'

In [34]:
# pd.DataFrame(risks_df)
print(high_risk[high_risk.Department == "Design"].index == [])

[]